List<String> QUOTES = [
  "PLEASE WEAR YOUR MASKS TILL WE FIND YOUR DATA.",
  "DID YOU KNOW ALL OUR HOSPITAL DATA ARE TAKEN FROM OFFICIAL WEBSITES?",
  "DON'T FORGET TO SANITISE YOUR HANDS WHILE WE FIND YOUR DATA.",
  "MAINTAIN A SAFE DISTANCE FROM PEOPLE NEAR YOU WHILE WE FETCH YOUR DATA.",
  "DID YOU KNOW THAT in-COVID WAS A REJECTED HACKATHON PROJECT?",
  "STAY MENTALLY POSITIVE, BETTER DAYS ARE ON THEIR WAY.",
  "KEEP FEELING POSITIVE AND TESTING NEGATIVE.",
];

// "ROSES ARE RED, LEAVES ARE GREEN, I HOPE YOU TESTED NEGATIVE FOR COVID 19.",
// "ROSES ARE RED, THIS AIN'T THE FLU, IF YOU THINK OTHERWISE, YOU DONT HAVE A CLUE.",
// "ROSES ARE RED, VIOLETS ARE BLUE, I AM SENDING HUGS, ESPECIALLY FOR YOU ;)",
